[tools]
rojo = "rojo-rbx/rojo@7.7.0-rc.1"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.6.2"
selene = "Kampfkarren/selene@0.29.0"
stylua = "johnnymorganz/stylua@2.3.1"
luau-lsp = "JohnnyMorganz/luau-lsp@1.58.0"
lune = "lune-org/lune@0.10.4"
roblox-packages = "flipbook-labs/roblox-packages@0.3.0"
